services:
  makblogii:
    build: .
    container_name: makblogii_container
    ports:
      - "7777:8000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/test
      - NODE_ENV=development
      - PORT=8000
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=test
    restart: unless-stopped

volumes:
  mongo-data:
